### ISSUE TITLE
개발 방법론과 개발 패러다임에 대한 이해

### ISSUE THREAD

**Issue by psyoblade** [ncsoft-dit-public/coffeeprince#4]
카톡을 통해 주고 받았던 용어에 대해 제가 이해한 수준에서 정리해 보았는데요, 의견 부탁 드립니다.

### 도메인 주도 개발 (Domain Driven Development)
> 도메인 주도 개발은 하나의 개발 방법론이며, 실제 구현의 패러다임과는 무관하게 적용할 수 있다
<br>

### 객체 지향 프로그래밍 (Object Oriented Programming)
> 객체를 기준으로 상태를 변경하며 관리하는 방식
### 함수형 프로그래밍 (Functional Programming)
> 함수를 기준으로 새로운 상태를 가진 객체를 활용하는 방식

**Comment by leeyh0216** [comment]
1번의 경우 기술하신 내용이 맞습니다.
도메인 주도 개발, 테스트 주도 개발, 티켓 주도 개발 등 다양한 개발 방법론이 있습니다.
[위키피디아 - 소프트웨어 개발 방법론](https://ko.wikipedia.org/wiki/%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4_%EA%B0%9C%EB%B0%9C_%EB%B0%A9%EB%B2%95%EB%A1%A0) 페이지를 참고하면 좋을 것 같습니다.

2번의 경우 객체 지향 프로그래밍의 정의가 약간은 난해하지만, 비슷하게 정리된 것 같습니다.
패러다임은 언어와 구현의 방향성을 강조하는 느낌이 더 드는 것 같습니다.

**Comment by psyoblade** [comment]
https://multicore-it.com/46 자료를 보면 막연히 생각했던 개발방법론과 패러다임의 차이는 없어 보이네요 ;-)

**Comment by leeyh0216** [comment]
개발 방법론은
  * 프로그래밍 언어
  * 소프트웨어 공학
관점에서 다르게 해석이 가능하다.
 
프로그래밍 개발 방법론으로는 명령형, 함수형, 객체지향 등이 존재한다.
소프트웨어 공학 개발 방법론으로는 TDD, BDD, DDD 등이 존재한다.
